### ISSUE TITLE
No Spelling Errors Dialog

### ISSUE THREAD

**Issue by thunsaker** [ethology-co/sketch-spellcheck-all-layers#10]
When a document contains no spelling errors, the UI should indicate as much. This could be an opportunity to have some fun and congratulate the user for such a finely worded document.

This could also handle scenarios where there is no text to be checked.

Request via [Twitter](https://twitter.com/thunsaker/status/819202388376440832)

**Comment by seanriceaz** [comment]
Adding this into the 1.0 Release milestone.
