### ISSUE TITLE
Unable to Close if Dialog Longer Than Screen

### ISSUE THREAD

**Issue by rajohnson424** [ethology-co/sketch-spellcheck-all-layers#4]
If the number of spelling errors exceeds the length of the page, the dialog drops below the screen and you are unable to click the close button, which is at the bottom right hand corner. There is no option in the top nav to close the dialog and it does not respond to COMMAND+W on mac (close tab)

<img width="813" alt="screen shot 2016-12-20 at 5 21 23 pm" src="https://cloud.githubusercontent.com/assets/20781764/21371865/52af7f82-c6d9-11e6-831e-3e1c25d3f118.png">

**Comment by rodnem** [comment]
arg... same here
![image](https://cloud.githubusercontent.com/assets/6350513/21382903/57f7dbee-c763-11e6-818d-abe8990c98d8.png)

**Comment by seanriceaz** [comment]
Thanks for reporting this!
I'm going to fix this for the next release.

**Comment by seanriceaz** [comment]
@rodnem and @rajohnson424 could you please let me know what version of OSX you are using? I'm not able to recreate the issue of the "OK" button not showing up.

For now, you should be able to press "return" to clear the dialog.

THOUGH, I do see that there's an issue with text overflowing the dialog box. I'm working on a fix for this, but it wasn't as simple as I had thought.

**Comment by rodnem** [comment]
I'm on os x 10.11.6 (can't update) with sketch 41.2

**Comment by seanriceaz** [comment]
@rodnem and @rajohnson424
I added in a much more robust spell checker. It's a lot more like the system one (which, for some reason, I can't use for this). In any case, this bug should no longer be an issue.

[Download version 0.9](https://github.com/ethology-co/sketch-spellcheck-all-layers/archive/master.zip) and let me know what you think of it!
